spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500
  mail:
    host: smtp.mailplug.co.kr
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.ssl.enable: true

server:
  port: ${PORT}
  ssl:
    enabled: false
  error:
    whitelabel:
      enabled: false
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: metrics
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

jwt:
  secret: ${JWT_SECRET}