spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500
  output:
    ansi:
      enabled: always

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: benope
  error:
    whitelabel:
      enabled: false
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: metrics
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

jwt:
  secret: secret