spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500

server:
  port: ${PORT}
  ssl:
    enabled: false
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: metrics
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

jwt:
  secret: ${JWT_SECRET}